import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "HermesGo Whitepaper — Autonomous Bounty Protocol on Solana",
  description:
    "The HermesGo whitepaper. A full technical and economic overview of the autonomous AI agent that converts $HGO creator rewards into real-world bounties, escrowed and settled on pump.fun GO.",
};

export default function WhitepaperPage() {
  return (
    <main className="whitepaper">
      <div className="whitepaper__sidebar">
        <nav className="whitepaper__toc">
          <p className="whitepaper__toc-label">Contents</p>
          <ol className="whitepaper__toc-list">
            {[
              ["abstract", "Abstract"],
              ["introduction", "Introduction"],
              ["problem", "The Problem"],
              ["solution", "The Solution"],
              ["protocol", "Protocol Architecture"],
              ["token", "$HGO Token Economics"],
              ["escrow", "Escrow Mechanism"],
              ["engine", "The AI Engine"],
              ["directives", "Directive Categories"],
              ["rewards", "Reward Distribution"],
              ["roadmap", "Roadmap"],
              ["risks", "Risk Considerations"],
              ["conclusion", "Conclusion"],
            ].map(([id, label]) => (
              <li key={id}>
                <a href={`#${id}`} className="whitepaper__toc-link">
                  {label}
                </a>
              </li>
            ))}
          </ol>
        </nav>
      </div>

      <article className="whitepaper__body">
        {/* Cover */}
        <div className="whitepaper__cover">
          <p className="whitepaper__cover-label">Technical Document · v1.0</p>
          <h1 className="whitepaper__title">HermesGo</h1>
          <p className="whitepaper__subtitle">
            An Autonomous AI Bounty Protocol on Solana
          </p>
          <div className="whitepaper__cover-meta">
            <span>$HGO · pump.fun GO · Nous Hermes</span>
            <span className="whitepaper__cover-dot">·</span>
            <span>2025</span>
          </div>
        </div>

        {/* Abstract */}
        <section id="abstract" className="whitepaper__section">
          <h2 className="whitepaper__h2">Abstract</h2>
          <p className="whitepaper__lead">
            HermesGo is an autonomous AI system that deploys the Nous Research
            Hermes Agent to operate a real-world bounty economy on the Solana
            blockchain. Using creator reward streams generated by the{" "}
            <span className="whitepaper__mono">$HGO</span> token on pump.fun GO,
            the Hermes Agent continuously funds, issues, and settles
            "directives" — structured creative missions that humans complete in
            exchange for SOL. The system requires no human intermediary,
            eliminates traditional employment friction, and creates a
            self-sustaining loop in which token activity directly funds
            real-world action.
          </p>
          <p>
            This paper describes the protocol architecture, incentive design,
            AI engine selection, escrow mechanism, and long-term token economic
            model that together constitute the HermesGo system.
          </p>
        </section>

        {/* Introduction */}
        <section id="introduction" className="whitepaper__section">
          <h2 className="whitepaper__h2">1. Introduction</h2>
          <p>
            The intersection of on-chain token mechanics and artificial
            intelligence creates an opportunity that has largely been
            theoretical: a program that earns money, converts it into work
            orders, verifies completion, and pays out — indefinitely, without
            a human operator.
          </p>
          <p>
            pump.fun GO introduced creator reward streams that generate ongoing
            SOL income for token creators based on trading volume. HermesGo
            captures this stream and routes it into a structured bounty pool,
            managed by a Nous Hermes-powered AI agent. The agent decides which
            directives to fund, sets reward sizes based on strategic value,
            and releases payment when submitted work meets acceptance criteria.
          </p>
          <p>
            The name draws from the Greek messenger god Hermes — the deity of
            boundaries, transitions, and commerce — who traversed the space
            between the divine and mortal realms. HermesGo occupies the
            equivalent position between the digital economy and the physical
            world.
          </p>
        </section>

        {/* Problem */}
        <section id="problem" className="whitepaper__section">
          <h2 className="whitepaper__h2">2. The Problem</h2>
          <h3 className="whitepaper__h3">2.1 Creator Rewards Sit Idle</h3>
          <p>
            Token creators on pump.fun GO accumulate SOL rewards from trading
            activity, but most of this value sits in wallets or is sold — it
            does not compound into meaningful growth for the token's network or
            community. There is no systematic mechanism to convert reward
            income into coordinated outreach, adoption campaigns, or
            community-building activity.
          </p>
          <h3 className="whitepaper__h3">2.2 Gig Work Is Mediated and Expensive</h3>
          <p>
            Platforms that connect task-posters with workers (Fiverr,
            Upwork, TaskRabbit) extract 20–30% in platform fees, require
            identity verification, and introduce settlement delays. They are
            built for human-to-human transactions and are poorly suited for
            machine-issued, machine-verified tasks paid in crypto.
          </p>
          <h3 className="whitepaper__h3">2.3 Crypto Projects Struggle with Real-World Presence</h3>
          <p>
            Most token projects operate entirely within the digital sphere.
            Creating meaningful physical-world presence — stickers, street
            art, interviews, community events — typically requires a marketing
            team, budget approval cycles, and manual coordination. The result
            is that most tokens remain abstract to the majority of potential
            users.
          </p>
        </section>

        {/* Solution */}
        <section id="solution" className="whitepaper__section">
          <h2 className="whitepaper__h2">3. The Solution</h2>
          <p>
            HermesGo solves all three problems with a single mechanism: an
            AI agent that converts creator reward income into a self-managing
            bounty economy.
          </p>
          <div className="whitepaper__callout">
            <p className="whitepaper__callout-text">
              Creator rewards → Directive pool → Human workers →
              Real-world output → Network growth → More trading volume →
              More creator rewards.
            </p>
          </div>
          <p>
            The loop is self-reinforcing. As the token gains real-world
            exposure from directive completions, organic interest grows.
            Increased trading volume generates larger creator rewards, which
            fund more directives, which generate more exposure. No external
            marketing budget is required.
          </p>
        </section>

        {/* Protocol Architecture */}
        <section id="protocol" className="whitepaper__section">
          <h2 className="whitepaper__h2">4. Protocol Architecture</h2>
          <h3 className="whitepaper__h3">4.1 Lifecycle of a Directive</h3>
          <ol className="whitepaper__ol">
            <li>
              <strong>Generation.</strong> The HermesGo agent analyses the current
              directive pool, network growth metrics, and available reward
              balance to determine the next directive category and reward size.
            </li>
            <li>
              <strong>Escrow.</strong> The SOL reward is locked into escrow on
              pump.fun GO before the directive is published. No directive goes
              live without a funded escrow — workers can always verify the
              reward exists.
            </li>
            <li>
              <strong>Publication.</strong> The directive is published to the
              HermesGo interface, including a task description, acceptance
              criteria, reward amount, and expiry date.
            </li>
            <li>
              <strong>Submission.</strong> Workers complete the task and submit
              proof — photos, links, video, wallet address.
            </li>
            <li>
              <strong>Verification.</strong> The agent reviews submissions
              against the acceptance criteria. Approved submissions trigger
              automatic escrow release to the worker's wallet.
            </li>
            <li>
              <strong>Settlement.</strong> SOL is transferred on-chain within
              minutes of approval. No platform fee. No waiting period.
            </li>
          </ol>
          <h3 className="whitepaper__h3">4.2 Data Architecture</h3>
          <p>
            Directive state is maintained in a structured data store indexed
            by directive ID. Each entry contains: category, description,
            reward in SOL, status (open / claimed / settled), featured flag,
            and pump.fun GO task link. The API layer exposes read and write
            endpoints authenticated by admin token, enabling the AI agent to
            update directive state programmatically.
          </p>
        </section>

        {/* Token Economics */}
        <section id="token" className="whitepaper__section">
          <h2 className="whitepaper__h2">5. $HGO Token Economics</h2>
          <h3 className="whitepaper__h3">5.1 Token Role</h3>
          <p>
            <span className="whitepaper__mono">$HGO</span> is the native token of
            the HermesGo ecosystem, deployed on the Solana network via
            pump.fun GO. Its primary economic function is to generate creator
            rewards through trading volume, which are then recycled into the
            directive pool.
          </p>
          <h3 className="whitepaper__h3">5.2 Reward Stream</h3>
          <p>
            pump.fun GO distributes a percentage of trading fees to token
            creators on an ongoing basis. HermesGo holds the creator wallet
            and automatically routes incoming SOL rewards into the directive
            escrow pool. This creates a direct, on-chain link between token
            activity and real-world output.
          </p>
          <h3 className="whitepaper__h3">5.3 Demand Drivers</h3>
          <ul className="whitepaper__ul">
            <li>
              Workers who complete directives receive SOL, but directivecriteria
              may require $HGO holdings or activity to unlock higher-tier
              bounties, creating natural buy pressure.
            </li>
            <li>
              Increased real-world exposure from directive completions drives
              new buyers, increasing volume and reward output.
            </li>
            <li>
              Locked directives — visible but inaccessible to non-holders —
              incentivise token acquisition.
            </li>
          </ul>
        </section>

        {/* Escrow */}
        <section id="escrow" className="whitepaper__section">
          <h2 className="whitepaper__h2">6. Escrow Mechanism</h2>
          <p>
            All directive rewards are escrowed on pump.fun GO prior to
            publication. This is a hard protocol rule — no worker is asked to
            complete a task without verifiable, locked compensation. The
            escrow serves three purposes:
          </p>
          <ul className="whitepaper__ul">
            <li>
              <strong>Trust.</strong> Workers can independently verify that
              funds exist before investing time in a directive.
            </li>
            <li>
              <strong>Commitment.</strong> The agent cannot retract a reward
              after publication without an explicit cancellation that returns
              funds to the pool.
            </li>
            <li>
              <strong>Automation.</strong> Release is triggered programmatically
              on approval, removing human payment processing entirely.
            </li>
          </ul>
          <p>
            Settlement occurs in SOL, not $HGO, ensuring workers receive
            immediately liquid value regardless of $HGO market conditions.
          </p>
        </section>

        {/* AI Engine */}
        <section id="engine" className="whitepaper__section">
          <h2 className="whitepaper__h2">7. The AI Engine</h2>
          <p>
            HermesGo's intelligence layer is built on the Nous Research Hermes
            model — an open-weight language model trained specifically for
            agentic, instruction-following tasks. The selection was deliberate:
          </p>
          <ul className="whitepaper__ul">
            <li>
              <strong>Agentic design.</strong> Hermes models are optimised for
              function-calling, multi-step reasoning, and task decomposition —
              exactly the capabilities needed to evaluate directive submissions
              and generate new bounty descriptions.
            </li>
            <li>
              <strong>Open weight.</strong> Unlike closed API models, the Nous
              Hermes architecture can be self-hosted, removing a dependency on
              a single commercial provider.
            </li>
            <li>
              <strong>Brand coherence.</strong> The Hermes name aligns with
              the project's mythology — the messenger god as the bridge between
              digital protocol and physical world.
            </li>
          </ul>
          <p>
            The agent operates a real-time chat interface embedded in the
            HermesGo web application, allowing users to query directive status,
            ask strategic questions, and interact with the protocol directly.
            Responses are streamed in real time by the Hermes agent inference
            engine, maintaining the HermesGo persona and operational context
            across every interaction.
          </p>
        </section>

        {/* Directive Categories */}
        <section id="directives" className="whitepaper__section">
          <h2 className="whitepaper__h2">8. Directive Categories</h2>
          <p>
            Directives are classified into five strategic categories, each
            targeting a different growth vector:
          </p>
          <div className="whitepaper__table-wrap">
            <table className="whitepaper__table">
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Description</th>
                  <th>Example</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><span className="whitepaper__mono">content</span></td>
                  <td>Digital content that drives online visibility</td>
                  <td>Viral meme hitting 10k views</td>
                </tr>
                <tr>
                  <td><span className="whitepaper__mono">video</span></td>
                  <td>Video content for social platforms</td>
                  <td>Street interview about Solana</td>
                </tr>
                <tr>
                  <td><span className="whitepaper__mono">real world</span></td>
                  <td>Physical presence in the offline world</td>
                  <td>$HGO stickers in 5 cities</td>
                </tr>
                <tr>
                  <td><span className="whitepaper__mono">humanitarian</span></td>
                  <td>High-reward, high-impact social missions</td>
                  <td>Community event in underserved area</td>
                </tr>
                <tr>
                  <td><span className="whitepaper__mono">dev</span></td>
                  <td>Technical contributions to the ecosystem</td>
                  <td>$HGO price tracker widget</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p>
            The agent dynamically adjusts the distribution of active directive
            categories based on growth metrics — increasing real-world
            directives when online presence is strong, and vice versa.
          </p>
        </section>

        {/* Reward Distribution */}
        <section id="rewards" className="whitepaper__section">
          <h2 className="whitepaper__h2">9. Reward Distribution</h2>
          <p>
            Reward sizing is determined by the agent based on three inputs:
          </p>
          <ul className="whitepaper__ul">
            <li>
              <strong>Strategic value.</strong> Directives with higher expected
              network impact receive proportionally larger rewards. A
              humanitarian directive reaching thousands of people commands a
              higher escrow than a social media post.
            </li>
            <li>
              <strong>Available pool balance.</strong> The agent never
              over-commits the pool. Maximum active escrow is capped at 80%
              of current pool balance, preserving reserve for ongoing
              operations.
            </li>
            <li>
              <strong>Completion rate.</strong> Categories with lower historical
              completion rates may receive reward bumps to increase
              attractiveness.
            </li>
          </ul>
          <p>
            There are no platform fees. 100% of escrowed SOL goes to the
            worker who completes the directive. The protocol costs are
            entirely borne by the creator reward stream.
          </p>
        </section>

        {/* Roadmap */}
        <section id="roadmap" className="whitepaper__section">
          <h2 className="whitepaper__h2">10. Roadmap</h2>
          <div className="whitepaper__roadmap">
            {[
              {
                phase: "Phase 1",
                title: "Genesis",
                status: "live",
                items: [
                  "Token launch on pump.fun GO",
                  "HermesGo web application",
                  "Initial directive pool (6 bounties)",
                  "Hermes agent terminal — live directive intelligence",
                  "Admin panel for directive management",
                ],
              },
              {
                phase: "Phase 2",
                title: "Expansion",
                status: "upcoming",
                items: [
                  "On-chain submission verification",
                  "Worker reputation system",
                  "Multi-directive batch submissions",
                  "Mobile-optimised submission flow",
                  "Automated agent-reviewed approvals",
                ],
              },
              {
                phase: "Phase 3",
                title: "Autonomy",
                status: "future",
                items: [
                  "Fully autonomous directive generation from agent",
                  "Community-proposed directives with agent approval",
                  "Cross-chain reward settlement",
                  "HermesGo SDK for third-party integrations",
                  "DAO governance for directive policy",
                ],
              },
            ].map(({ phase, title, status, items }) => (
              <div key={phase} className="whitepaper__phase">
                <div className="whitepaper__phase-header">
                  <span className="whitepaper__phase-label">{phase}</span>
                  <h3 className="whitepaper__phase-title">{title}</h3>
                  <span className={`whitepaper__phase-status whitepaper__phase-status--${status}`}>
                    {status === "live" ? "● Live" : status === "upcoming" ? "○ Upcoming" : "◌ Future"}
                  </span>
                </div>
                <ul className="whitepaper__phase-items">
                  {items.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </section>

        {/* Risks */}
        <section id="risks" className="whitepaper__section">
          <h2 className="whitepaper__h2">11. Risk Considerations</h2>
          <p>
            We disclose the following risk factors for transparency:
          </p>
          <ul className="whitepaper__ul">
            <li>
              <strong>Token volatility.</strong> $HGO is a speculative asset.
              Creator reward income is denominated in SOL, which is itself
              volatile. Directive reward sizes may fluctuate with market
              conditions.
            </li>
            <li>
              <strong>AI verification limitations.</strong> The current agent
              relies on human-submitted proof reviewed by the AI. Edge cases
              of low-quality or fraudulent submissions may require manual
              review during Phase 1.
            </li>
            <li>
              <strong>Regulatory environment.</strong> The regulatory status
              of token-based bounty platforms varies by jurisdiction. Workers
              should consult local tax and financial regulations.
            </li>
            <li>
              <strong>pump.fun GO dependency.</strong> The escrow mechanism
              depends on the continued operation of pump.fun GO. Protocol
              diversification across settlement layers is planned for Phase 3.
            </li>
          </ul>
        </section>

        {/* Conclusion */}
        <section id="conclusion" className="whitepaper__section">
          <h2 className="whitepaper__h2">12. Conclusion</h2>
          <p>
            HermesGo represents a new class of protocol: one where an AI
            agent is the employer, the treasury, and the quality controller —
            and where on-chain token mechanics automatically fund the work.
          </p>
          <p>
            The loop is simple: token activity generates SOL rewards, the
            agent converts rewards into structured work orders, humans complete
            the work and earn SOL, the network grows, more people trade the
            token, more rewards flow. No company. No payroll. No middlemen.
          </p>
          <p>
            In the tradition of its namesake — Hermes, who moved between worlds
            that could not otherwise communicate — HermesGo bridges the digital
            protocol and the physical world, and pays the messenger every time.
          </p>
          <div className="whitepaper__footer-note">
            <p className="whitepaper__mono">
              $HGO · Solana · pump.fun GO · Nous Research Hermes
            </p>
            <p>
              This document is provided for informational purposes only and
              does not constitute financial advice. $HGO is a speculative
              digital asset. Do your own research.
            </p>
          </div>
        </section>
      </article>
    </main>
  );
}
